sorted module list
underscorgan/community_management pull request #67
Opened 2019-11-05 07:31 UTC by daianamezdrea

2019-11-05 12:00 UTC, tphoney requested changes
There are a few things to clean up first

2019-11-05 12:00 UTC, tphoney commented on daily_open_prs.rb
> +CSV.open("pr_work_done.csv", "w") do |csv|
this look strange

2019-11-05 12:00 UTC, tphoney commented on release_planning.rb
> +require_relative 'release_planning/pupet_module'
sorry to be a debbie downer, the javascript plugins will not work in jenkins. due to the over zealous lock down there.

2019-11-05 12:00 UTC, tphoney commented on release_planning/pupet_module.rb
> +class PuppetModule
this is not used by anything outside of the release scripts. it should just live in the release planning script

2019-11-05 12:00 UTC, tphoney commented on release_planning/puppet_module_augmenter.rb
> +class PuppetModuleAugmenter
this is not used by anything outside of the release scripts. it should just live in the release planning script

2019-11-07 08:35 UTC, daianamezdrea commented
replaced by https://github.com/underscorgan/community_management/pull/68

2019-11-07 08:35 UTC, closed without merging