update release_modules.rb
underscorgan/community_management pull request #68
Opened 2019-11-07 08:35 UTC by daianamezdrea

2019-11-07 09:01 UTC, DavidS requested changes
some change requests below.

Please also improve the commit message to explain what this change is about. see e.g. https://who-t.blogspot.com/2009/12/on-commit-messages.html

2019-11-07 09:01 UTC, DavidS commented on release_planning.rb
> +end
indentation got messed up here.

2019-11-07 09:01 UTC, DavidS commented on release_planning.rb
> +PuppetModuleAugmenter.new.augment!(puppet_modules)
unnecessary memory allocation: you can define the method as `def self.augment!(...` and remove the `new` here to avoid creating an object instance you don't need.

2019-11-07 09:01 UTC, DavidS commented on octokit_utils.rb
> +'cisco_ios-private',
this `-private` repo can be removed - it's unused.

2019-11-07 09:01 UTC, DavidS commented on release_planning.rb
> +       if puppet_module.name == "cisco_ios"
Rather than hardcoding the special case here (and missing the other problematic case `cisco-network-puppet-module`) maybe we need to consider breaking up the `SUPPORTED_MODULES` data structure from badly defined strings into something that has github namespace, repo name, forge namespace, and module name as separate values?

2019-11-07 09:01 UTC, DavidS commented on release_planning.rb
> +end
(maybe an opportunity to enable rubocop for this repo)

2019-11-28 08:33 UTC, carabasdaniel commented on octokit_utils.rb
> +    return_val[:statuses] = client.statuses(repo, pr.head.sha) if filter.include? :statuses
pr variable is not defined here

2019-11-28 08:34 UTC, carabasdaniel commented on octokit_utils.rb
> +        while pr == mutex.synchronize { prs1.pop }
Should be an assignment not a comparisson

2019-11-28 09:31 UTC, carabasdaniel commented on daily_open_prs.rb
>    opts.on('-r', '--repo-regex REGEX', 'Repository regex') { |v| options[:repo_regex] = v }
Are these parameters used ? Once the modules.json has been defined it already contains the namespace

2019-11-28 09:31 UTC, carabasdaniel commented on daily_open_prs.rb
>  end
Default filters should not be needed anymore

2019-11-28 09:32 UTC, carabasdaniel commented on daily_open_prs.rb
>  missing << '-n' if options[:namespace].nil?
This should not be a required parameter anymore

2019-11-28 09:33 UTC, carabasdaniel commented on daily_open_prs.rb
> +  pr_cache = util.fetch_async("#{options[:namespace]}/#{repo}", search_with, filter)
Why are the options[:namespace] and {repo} used here, shouldn't this be the parsed data from the modules.json ?

2019-11-28 09:34 UTC, carabasdaniel commented on graph.rb
> +if option_selected.zero
it should be option_selected.zero?

2019-11-28 09:35 UTC, carabasdaniel commented on graph.rb
> +option_selected.zero
can be kept as option_selected = 0 for clarity

2019-11-28 09:35 UTC, carabasdaniel commented on labels.rb
>    opts.on('-r', '--repo-regex REGEX', 'Repository regex') { |v| options[:repo_regex] = v }
These parameters should not be needed anymore

2019-11-28 09:36 UTC, carabasdaniel commented on labels.rb
>  end
Default filters can be removed as the initial data should be received from modules.json

2019-11-28 09:38 UTC, carabasdaniel commented on labels.rb
> +  next unless options[:fix_labels]
In this block next unless could be replaced with an elsif followin the initial delete labels option and execute the utils functions only if the fix_labels option has been specified

2019-11-28 09:39 UTC, carabasdaniel commented on npc.rb
>    opts.on('-r', '--repo-regex REGEX', 'Repository regex') { |v| options[:repo_regex] = v }
These parameters should not be needed anymore if the modules.json file is used

2019-11-28 09:39 UTC, carabasdaniel commented on npc.rb
> +  next unless options[:merge_conflicts]
This should be a clear if statement

2019-11-28 09:40 UTC, carabasdaniel commented on npc.rb
> +  prs = util.fetch_pull_requests("#{options[:namespace]}/#{repo}")
nemspace and repo should be obtained from the modules.json file

2019-11-28 09:41 UTC, carabasdaniel commented on npc.rb
> +        util.remove_label_from_pr("#{options[:namespace]}/#{repo}", pr.number, 'needs-rebase') unless options[:no_op]
namespace and repository should be obtained from modules.json

2019-11-28 09:41 UTC, carabasdaniel commented on npc.rb
> +    pr_has_label = util.does_pr_have_label("#{options[:namespace]}/#{repo}", pr.number, 'needs-rebase')
namespace and repository should be obtained from modules.json

2019-11-28 09:43 UTC, carabasdaniel commented on octokit_utils.rb
>    def list_repos(namespace, options)
Method not used

2019-11-28 09:45 UTC, carabasdaniel commented on pr_review_list.rb
>  end
Default filters should not be needed anymore

2019-11-28 09:45 UTC, carabasdaniel commented on pr_review_list.rb
> +  pr_information_cache = util.fetch_async("#{options[:namespace]}/#{repo}")
Information cache should be obtained from modules.json entities

2019-11-28 09:46 UTC, carabasdaniel commented on pr_review_list.rb
>        html.push("<td><a href='https://github.com/#{options[:namespace]}/#{repo_name}/pull/#{value}'>#{value}</a></td>")
Please fix links for modules

2019-11-28 09:47 UTC, carabasdaniel commented on pr_work_done.rb
>  end
Default filters not needed anymore

2019-11-28 09:47 UTC, carabasdaniel commented on pr_work_done.rb
>  missing << '-n' if options[:namespace].nil?
Namespace should not be a parameter anymore

2019-11-28 09:47 UTC, carabasdaniel commented on pr_work_done.rb
> +  closed_pr_information_cache = util.fetch_async("#{options[:namespace]}/#{repo}} ")
namespace and repository information should be obtained from the modules.json entities

2019-11-28 09:52 UTC, carabasdaniel commented on pull_requests.rb
> +  end
Namespace and repository regex default filters should not be needed anymore with the addition of modules.json

2019-11-28 09:53 UTC, carabasdaniel commented on pull_requests.rb
> +  pr_information_cache = util.fetch_async("#{options[:namespace]}/#{repo}")
namespace and repository should be obtained from the modules.json entities

2019-11-28 09:55 UTC, carabasdaniel commented on release_planning.rb
> +class PuppetModule
This is not used as the objects obtained from json parse of modules.json should contain the necessary data

2019-11-28 09:55 UTC, carabasdaniel commented on release_planning.rb
>  missing << '-n' if options[:namespace].nil?
Namepace parameter should be removed

2019-11-28 09:56 UTC, carabasdaniel commented on release_planning.rb
>    opts.on('-n', '--namespace NAME', 'GitHub namespace. Required.') { |v| options[:namespace] = v }
Namespace is obtained from modules.json

2019-11-28 09:56 UTC, carabasdaniel commented on release_planning.rb
> +# repos = util.list_repos(options[:namespace], options)
Remove unused line

2019-11-28 09:57 UTC, carabasdaniel commented on release_planning.rb
> +  html.push("<td>#{puppet_module['repo']}</td>")
Set this up as a link to the module repository

2019-11-28 09:59 UTC, carabasdaniel requested changes
Please resolve the above comments

2019-12-03 09:19 UTC, DavidS commented on modules.json
> +    "repo_name": "puppetlabs-websphere_application_server",
duplicate entry - see L16. 

would be nice to have a formatter/checker for this file that keeps it in alphabetical order and checks for duplicates and missing keys.

2019-12-03 10:49 UTC, carabasdaniel requested changes

2019-12-03 10:49 UTC, carabasdaniel commented on npc.rb
> +    puts "XXX #{pr.number}"
Remove debugging "puts"

2019-12-03 10:49 UTC, carabasdaniel commented on pull_requests.rb
> +  # opts.on('-r', '--repo-regex REGEX', 'Repository regex') { |v| options[:repo_regex] = v }
These options can be removed

2019-12-03 10:49 UTC, carabasdaniel commented on pull_requests.rb
> +  # end
Default filters can be removed

2019-12-03 10:49 UTC, carabasdaniel commented on pull_requests.rb
> +#repos = util.list_repos(options[:namespace], options)
Line can be removed

2019-12-03 10:49 UTC, carabasdaniel commented on release_planning.rb
> +parsed1 = JSON.parse(output)
Variable naming consistency

2019-12-09 08:43 UTC, carabasdaniel approved these changes

2019-12-09 10:10 UTC, bastelfreak commented on daily_open_prs.rb
> -  opts.on('--community', 'Select community modules') {
Hi @daianamezdrea Vox Pupuli still uses this. Is it possible to keep this option?

2019-12-09 10:38 UTC, DavidS requested changes
a number of comments re coding and functionality inline.

2019-12-09 10:38 UTC, DavidS commented on .gitignore
> +.DS_Store
Please squash the DS_Store deletion commits into the commit that added them to avoid having them stored in the repo at all

2019-12-09 10:38 UTC, DavidS commented on .rubocop.yml
> +Metrics/LineLength:
Where do those rules come from? It is not looking like one of our common files.

2019-12-09 10:38 UTC, DavidS commented on daily_open_prs.rb
> +output = File.read('modules.json')
To make this at least nominally useful to folks outside the company, please make the loaded file a command line option. It can default to this value.

2019-12-09 10:38 UTC, DavidS commented on daily_open_prs.rb
> +parsed = JSON.parse(output)
This duplicated code can move to octokit_utils (e.g. `load_module_list`) and move below the option parsing (see comment above). No need to load the file when there is a invalid option or just `--help`.

2019-12-09 10:38 UTC, DavidS commented on labels.rb
> -  opts.on('--voxpupuli', 'Select voxpupuli modules') {
Vox is still using these scripts with this option. Please ensure that all of them still can be used in this way.

Following up on the "duplicated json loading code" comment, this also could be unified in the utils code to have a single definition for the default options.

2019-12-09 10:38 UTC, DavidS commented on modules.json
> +    "forge_name": "puppetlabs-accounts"
there is only one use of `forge_name` in the code today, but mushing together the forge namespace and the module name into one values makes it a lot harder to use the data elsewhere.

2019-12-09 10:38 UTC, DavidS commented on modules.json
> +    "module_name": "network-puppet-module",
the module is called "ciscopuppet"

2019-12-09 10:38 UTC, DavidS commented on release_planning.rb
> +html.push('<html>')
@carabasdaniel is it time to move this into a ERB template?

2019-12-09 10:38 UTC, DavidS commented on release_planning.rb
> +  File.open('ModulesRelease.html', 'w+') do |f|
doesn't need the `+` - no read access to the file.

2019-12-09 10:38 UTC, DavidS commented on release_planning.rb
> +  File.open('ModulesRelease.json', 'w') do |f|
Please open all files in binary mode (`'wb'` see https://ruby-doc.org/core-2.1.4/IO.html#method-c-new) so that the files work across all platforms.

2019-12-09 10:38 UTC, DavidS commented on stats.rb
> +  # rubocop:enable Lint/UselessAssignment
rubocop is right here. The assignments to `search_with` and `filter` are useless: the value is not used below. If the intention of this was to use named arguments, please use the correct ruby syntax for this.

2019-12-11 08:19 UTC, closed without merging

2019-12-11 08:20 UTC, daianamezdrea commented
Replaced by PR : https://github.com/underscorgan/community_management/pull/69