Add search bar for release_planning.rb and pr_review_list.rb
underscorgan/community_management pull request #70
Opened 2019-12-12 09:11 UTC by daianamezdrea

Depends on PR : https://github.com/underscorgan/community_management/pull/69

2019-12-12 11:34 UTC, sanfrancrisko requested changes
Minor comments, otherwise LGTM. My JS reviewing abilities are low, so probably nothing of value to offer there! 😆

2019-12-12 11:34 UTC, cmccrisken-puppet commented on npc.rb
> +    puts pr_merges
Perhaps move `puts pr_merges` after the `if pr_merges` on line 48 - we could end up with an output of `nil` otherwise.

2019-12-12 11:34 UTC, cmccrisken-puppet commented on octokit_utils.rb
> +      Thread.new(prs, pr_information_cache) do |prs1, pr_information_cache1|
Not sure about the `1` in the var names

2019-12-12 11:34 UTC, cmccrisken-puppet commented on stats.rb
> +puts 'repo, last comment, needs rebase, fails test, needs squash, no comments, total open, has mention, no activty 40 days'
Add a `unless parsed.empty?` to prevent unnecessary `puts` in the event of an empty array

2019-12-17 11:26 UTC, DavidS approved these changes
I could run a subset of the reports locally fine.

2019-12-17 11:26 UTC, merged